name: UI Tests for Restfull booker frontend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  ui-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Run UI Tests in Docker
        run: docker-compose up --build --abort-on-container-exit

      - name: Install Allure CLI
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
          tar -zxvf allure-2.27.0.tgz
          sudo mv allure-2.27.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure

      - name: Generate Allure Report
        run: |
          export ALLURE_BASE_PATH=/RestfullBookerFrontend
          sudo chown -R $USER:$USER ./allure-report || true
          rm -rf ./allure-report
          mkdir -p ./allure-report
          allure generate ./allure-results --clean -o ./allure-report

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report


  deploy-allure-report:
    needs: ui-tests
    runs-on: ubuntu-latest

    steps:
      - name: Download Allure Results
        uses: actions/download-artifact@v3.0.2
        with:
          name: allure-results
          path: allure-results

      - name: Generate Allure Report
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
          tar -zxvf allure-2.27.0.tgz
          ./allure-2.27.0/bin/allure generate allure-results -o allure-report --clean

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report
